development:
  dialect: postgres
  database: wecarry
  user: wecarry
  password: wecarry
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://wecarry:wecarry@testdb:5432/wecarry_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://wecarry:wecarry@127.0.0.1:5432/wecarry_production?sslmode=disable"}}
