checks:
  go: true
build:
  environment:
    go: go1.16.4
    variables:
      GO_ENV: test
      EMAIL_SERVICE: dummy
      AWS_S3_ENDPOINT: http://localhost:9000
      AWS_ACCESS_KEY_ID: abc123
      AWS_SECRET_ACCESS_KEY: abcd1234
      AWS_S3_DISABLE_SSL: true
      AWS_S3_BUCKET: wca-test-bucket
      AWS_DEFAULT_REGION: us-east-1
      FACEBOOK_KEY: test
      FACEBOOK_SECRET: test
      GOOGLE_KEY: test
      GOOGLE_SECRET: test
      SERVICE_INTEGRATION_TOKEN: abc123test
      TEST_DATABASE_URL: postgres://scrutinizer:scrutinizer@localhost:5432/scrutinizer?sslmode=disable
      DISABLE_TLS: true
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
    coverage:
      services:
        postgres: 11.5
        minio:
          image: silintl/minio-default-server
          ports:
            - 9000
          env:
            MINIO_ACCESS_KEY: abc123
            MINIO_SECRET_KEY: abcd1234
          ramdisks:
            - /data
      tests:
        override:
          - command: ./scrutinizer-test.sh
            coverage:
              file: 'cover.out'
              format: 'go-cc'
  root_path: './application'
filter:
  excluded_paths:
    - "*_test.go"
    - "*_fixtures_test.go"
    - "application/gqlgen/generated.go"
    - "application/gqlgen/models_gen.go"
