version: "2.4"

services:
  buffalo:
    build:
      context: ./application
      dockerfile: Dockerfile-dev
    volumes:
      - ./application:/wecarry
    ports:
      - "3000:3000"
      - "6060"
    env_file:
      - local.env
    environment:
      ADDR: 0.0.0.0
      HOST: https://local.wecarry.app
      # Needed for Google and AzureAD OAuth locally
      # HOST: http://localhost:3000
      PORT: 3000
      APP_NAME: Local WeCarry
      DATABASE_URL: postgres://wecarry:wecarry@db:5432/wecarry?sslmode=disable
      GO_ENV: development
      SUPPORT_EMAIL: forget_about_it@example.com
    depends_on:
      - db
      - minio
      - redis
    command: buffalo dev
    mem_limit: 2000m

  test:
    build:
      context: ./application
      dockerfile: Dockerfile-dev
    volumes:
      - ./application:/wecarry
    env_file:
      - ./test.env
    environment:
      EMAIL_SERVICE: dummy
      GO_ENV: test
      DOCKER_IP: testdb
      FACEBOOK_KEY: test
      FACEBOOK_SECRET: test
      GOOGLE_KEY: test
      GOOGLE_SECRET: test
      HISTCONTROL: ignoreboth:erasedups
      LOG_LEVEL: fatal
    depends_on:
      - testdb
      - minio
      - redis
    working_dir: /wecarry
    command: buffalo test

  db:
    image: postgres:11.6
    volumes:
      - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    environment:
      POSTGRES_USER: wecarry
      POSTGRES_PASSWORD: wecarry
      POSTGRES_DB: wecarry

  testdb:
    image: postgres:11.6
    environment:
      POSTGRES_USER: wecarry
      POSTGRES_PASSWORD: wecarry
      POSTGRES_DB: wecarry_test

  # http://localhost:8080/?pgsql=db&username=wecarry&db=wecarry&ns=public
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data
    env_file:
      - local.env
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf

  swagger:
    image: quay.io/goswagger/swagger:latest
    ports:
      - "8082:8082"
    volumes:
      - ./application/:/app
    working_dir: /app

  debug:
    build:
      context: ./application
      dockerfile: Dockerfile-dev
    volumes:
      - ./application:/wecarry
    env_file:
      - local.env
    ports:
      - 2345:2345
      - 3000:3000
    environment:
      ADDR: 0.0.0.0
      HOST: https://local.wecarry.app
      # Needed for Google and AzureAD OAuth locally
      # HOST: http://localhost:3000
      PORT: 3000
      APP_NAME: Local WeCarry
      DATABASE_URL: postgres://wecarry:wecarry@db:5432/wecarry?sslmode=disable
      GO_ENV: development
      SUPPORT_EMAIL: forget_about_it@example.com
    depends_on:
      - db
      - minio
    command: ./debug.sh

  gosec:
    image: securego/gosec:latest
    volumes:
      - ./application:/wecarry
    # Remember to make the exclude value match the corresponding line in codeship-test.sh
    command: ["-exclude=G104", "-quiet", "/wecarry/..."]
