version: "3.7"

services:
  buffalo:
    build:
      context: ./application
      dockerfile: Dockerfile-dev
    volumes:
      - ./application:/wecarry
      - ./dev:/wecarry/dev
    ports:
      - "3000:3000"
      - "6060"
    env_file:
      - .env
    environment:
      ADDR: 0.0.0.0
      HOST: https://local.wecarry.app
      # Needed for Google and AzureAD OAuth locally
      # HOST: http://localhost:3000
      PORT: 3000
      APP_NAME: Local WeCarry
      UI_URL: http://wecarry.local:5000
      DATABASE_URL: postgres://wecarry:wecarry@db:5432/wecarry?sslmode=disable
      GO_ENV: development
      SUPPORT_EMAIL: forget_about_it@example.com
    depends_on:
      - db
      - minio
    command: buffalo dev

  test:
    build:
      context: ./application
      dockerfile: Dockerfile-dev
    volumes:
      - ./application:/wecarry
    env_file:
      - ./test.env
    environment:
      EMAIL_SERVICE: dummy
      GO_ENV: test
      DOCKER_IP: testdb
      FACEBOOK_KEY: test
      FACEBOOK_SECRET: test
      GOOGLE_KEY: test
      GOOGLE_SECRET: test
      HISTCONTROL: ignoreboth:erasedups
      LOG_LEVEL: fatal
    depends_on:
      - testdb
      - minio
    working_dir: /wecarry
    command: buffalo test

  db:
    image: postgres:11.6
    environment:
      POSTGRES_USER: wecarry
      POSTGRES_PASSWORD: wecarry
      POSTGRES_DB: wecarry

  testdb:
    image: postgres:11.6
    environment:
      POSTGRES_USER: wecarry
      POSTGRES_PASSWORD: wecarry
      POSTGRES_DB: wecarry_test

  # http://localhost:8080/?pgsql=db&username=wecarry&db=wecarry&ns=public
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
