apiVersion: v1
kind: Service
metadata:
  name: wecarry
  labels:
    app: wecarry
spec:
  ports:
    - port: 3000
  selector:
    app: wecarry
    tier: middle
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wecarry
  labels:
    app: wecarry
spec:
  selector:
    matchLabels:
      app: wecarry
      tier: middle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wecarry
        tier: middle
    spec:
      containers:
      - image: wecarry-api_buffalo
        imagePullPolicy: Never
        name: wecarry
        env:
        - name: ADDR
          value: 0.0.0.0
        - name: HOST
          value: http://wecarry.local:3000
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
          name: wecarry
